# Production override for Docker Compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: "3.8"

services:
  mcp-server:
    build:
      target: production
    environment:
      - AGENTIC_CONVERTER_ENV=production
      - AGENTIC_CONVERTER_CONFIG_FILE=/app/config/production.json
      - AGENTIC_CONVERTER_LOG_LEVEL=INFO
    volumes:
      # Production: only mount data and config, not source code
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "1.0"
          memory: 2G

  http-server:
    build:
      target: production
    environment:
      - AGENTIC_CONVERTER_ENV=production
      - AGENTIC_CONVERTER_CONFIG_FILE=/app/config/production.json
      - AGENTIC_CONVERTER_LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G

  redis:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M

  postgres:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.2"
          memory: 256M
