version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(levelname)s:     %(name)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stderr

loggers:
  agentic_neurodata_conversion:
    level: INFO
    handlers: [console]
    propagate: false
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: false
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]
