"""
Observation Model.

Represents a metadata normalization observation with provenance.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class Observation(BaseModel):
    """Observation of a metadata field normalization."""

    observation_id: str | None = Field(None, description="UUID generated by Neo4j")
    field_path: str = Field(..., description="NWB field path", examples=["subject.species", "subject.sex"])
    raw_value: str = Field(..., description="Original input value")
    normalized_value: str | None = Field(None, description="Normalized value")
    ontology_term_id: str | None = Field(None, description="Ontology term ID")
    source_type: str = Field(
        ..., description="Source type (user/inferred/nwb_file/specification)", examples=["user", "inferred"]
    )
    source_file: str | None = Field(None, description="Source file name")
    confidence: float = Field(..., description="Confidence score (0.0-1.0)")
    provenance_json: dict[str, Any] = Field(default_factory=dict, description="Additional provenance data")
    created_at: datetime | None = Field(None, description="Creation timestamp")
    is_active: bool = Field(True, description="Whether observation is active")


class ObservationCreateRequest(BaseModel):
    """Request to create an observation."""

    field_path: str
    raw_value: str
    normalized_value: str | None = None
    ontology_term_id: str | None = None
    source_type: str
    source_file: str | None = None
    confidence: float
    provenance_json: dict[str, Any] = Field(default_factory=dict)


class ObservationResponse(BaseModel):
    """Response after creating observation."""

    observation_id: str
    status: str
