tools:
  nwbinspector:
    version: "0.4.0"
    run_command: "nwbinspector validate {file}"
  neuroconv:
    version: "0.3.2"
    run_command: "python -m neuroconv.validate {file}"
  linkml-validator:
    version: "1.7.1"
    schema_path: "./schemas/nwb_schema.yaml"
  knowledge-graph-checker:
    type: graph
    input: "./kg/nwb_ontology.ttl"
    rules: "./kg/rules.sparql"
