apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agentic-data-pvc
  namespace: agentic-neurodata
  labels:
    app.kubernetes.io/name: agentic-neurodata-conversion
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard # Adjust based on your cluster's storage classes
