blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/catalystneuro/agentic-neurodata-converter/tree/main/docs
    about: Check the project documentation for guides and API reference
  - name: Discussions
    url: https://github.com/catalystneuro/agentic-neurodata-converter/discussions
    about: Ask questions and discuss ideas with the community
  - name: CatalystNeuro Community
    url: https://github.com/catalystneuro
    about: Visit the broader CatalystNeuro community for related projects
