name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - MCP Server
        - Conversion Agent
        - Conversation Agent
        - Evaluation Agent
        - Knowledge Graph Agent
        - Configuration System
        - Data Management
        - Client Libraries
        - Documentation
        - New Component
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description:
        A clear and concise description of any alternative solutions or features
        you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Cannot proceed without this
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description:
        Describe your specific use case and how this feature would help
      placeholder: |
        I am working on... and need this feature to...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Add any other context, screenshots, or examples about the feature
        request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description:
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/catalystneuro/agentic-neurodata-converter/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
