name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please check the documentation first, then provide details below.

  - type: checkboxes
    id: documentation-check
    attributes:
      label: Documentation Check
      description: Have you checked the existing documentation?
      options:
        - label: I have checked the README
        - label: I have checked the API documentation
        - label: I have checked the examples directory
        - label: I have searched existing issues

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Installation and Setup
        - Configuration
        - Usage and Examples
        - MCP Server Integration
        - Agent Development
        - Data Conversion
        - Quality Assessment
        - Knowledge Graph
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description:
        Provide any relevant context about what you're trying to achieve
      placeholder: |
        I am trying to... and I need to understand...

  - type: textarea
    id: attempted
    attributes:
      label: What have you tried?
      description: Describe any solutions or approaches you've already attempted

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description:
        Provide environment details if they might be relevant to your question
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Python version: [e.g. 3.11.5]
        - Package version: [e.g. 1.0.0]

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description:
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/catalystneuro/agentic-neurodata-converter/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
