name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.56.0

      - name: Update pixi dependencies
        run: |
          pixi update

      - name: Run tests with updated dependencies
        run: |
          pixi install
          pixi run test-unit

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update pixi dependencies"
          title: "chore: update pixi dependencies"
          body: |
            Automated dependency update by GitHub Actions.

            This PR updates the pixi.lock file with the latest compatible versions.

            - Updated pixi dependencies
            - Verified unit tests pass with new versions

            Please review the changes and ensure all tests pass before merging.
          branch: chore/update-dependencies
          delete-branch: true

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.56.0

      - name: Install dependencies
        run: pixi install

      - name: Run security audit
        run: |
          pixi run safety check --json --output security-audit.json || true

      - name: Upload security audit results
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-${{ github.run_id }}
          path: security-audit.json

      - name: Create security issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try {
              const auditResults = JSON.parse(fs.readFileSync('security-audit.json', 'utf8'));
              if (auditResults.vulnerabilities && auditResults.vulnerabilities.length > 0) {
                const vulnerabilities = auditResults.vulnerabilities.map(v =>
                  `- **${v.package_name}** (${v.installed_version}): ${v.vulnerability_id}`
                ).join('\n');

                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: 'Security vulnerabilities detected in dependencies',
                  body: `Automated security scan detected vulnerabilities:\n\n${vulnerabilities}\n\nPlease review and update affected packages.`,
                  labels: ['security', 'dependencies', 'automated']
                });
              }
            } catch (error) {
              console.log('No security audit file found or parsing failed');
            }
