name: Quality Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.56.0
      - name: Install dependencies
        run: pixi install

      - name: Run quality checks
        run: pixi run quality

      - name: Run security analysis
        run: pixi run bandit -r agentic_neurodata_conversion/

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.56.0

      - name: Install dependencies
        run: pixi install

      - name: Check documentation links
        run: |
          find . -name "*.md" -exec markdown-link-check {} \; || true

      - name: Validate configuration files
        run: |
          pixi run python -c 'import json; json.load(open("config/default.json"))'
          pixi run python -c 'import tomllib; tomllib.load(open("pyproject.toml", "rb"))'

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.56.0

      - name: Install dependencies
        run: pixi install

      - name: Check for dependency vulnerabilities
        run: pixi run safety check --json --output safety-report.json || true

      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report-${{ github.sha }}
          path: safety-report.json
