name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.56.0

      - name: Install dependencies
        run: pixi install

      - name: Run full test suite
        run: |
          pixi run test-cov
          pixi run quality

      - name: Build package
        run: pixi run build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
          prerelease:
            ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') ||
            contains(github.ref, 'rc') }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
