name: Extended Testing

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      test_level:
        description: "Test level to run"
        required: true
        default: "integration"
        type: choice
        options:
          - integration
          - performance
          - mock_llm
          - small_model

jobs:
  extended-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.13.0

      - name: Install dependencies
        run: pixi install

      - name: Run integration tests
        if:
          ${{ github.event.inputs.test_level == 'integration' ||
          github.event_name == 'schedule' }}
        run: pixi run pytest -m "integration" -v --tb=short

      - name: Run performance tests
        if: ${{ github.event.inputs.test_level == 'performance' }}
        run: pixi run pytest -m "performance" -v --tb=short

      - name: Run mock LLM tests
        if: ${{ github.event.inputs.test_level == 'mock_llm' }}
        run: pixi run pytest -m "mock_llm" -v --tb=short

      - name: Run small model tests
        if: ${{ github.event.inputs.test_level == 'small_model' }}
        run: pixi run pytest -m "small_model" -v --tb=short

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: extended-test-results-${{ github.sha }}
          path: |
            pytest-report.xml
            coverage.xml
